nacos:
  server:
    addr: 193.112.137.231:8848

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server.addr}
        namespace: 3e362dcd-442c-4875-a04e-3b9d236f9c0d
        cluster-name: DEFAULT
    gateway:
      routes:
        - id: product_route
          uri: lb://wmall-product-web
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://wmall-member-web
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://wmall-ware-web
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}